#cloud-config
users:
  - name: cbeamer
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3GG+lA6Wm7XOk0hEgsip7qyNii/FWNO1YIlutbo4nA
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

packages:
  - python3
  - python3-pip
  - git
  - ansible

runcmd:
  - mkdir -p /app/python && cd /app/python && git clone https://github.com/Claire-Be/hello-world.git
  #- cd /app/python/hello-world/infrastructure/ansible/ && ansible-playbook self-config.yml