#cloud-config
users:
  - name: cbeamer
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3GG+lA6Wm7XOk0hEgsip7qyNii/FWNO1YIlutbo4nA
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

packages:
  - python3
  - python3-pip
  - ansible
  - git

runcmd:
  - mkdir -p /app/python && cd /app/python && git clone https://github.com/Claire-Be/hello-world.git
  - echo "[web]\nweb-1.dev.private\nweb-2.dev.private" >> /etc/ansible/hosts
  - sed -i s/#host_key_checking\ =\ False/host_key_checking\ =\ False/ /etc/ansible/ansible.cfg