#cloud-config
users:
  - name: ${remote_user}
    ssh_authorized_keys:
      - ${ssh_pub_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

packages:
  - python3
  - python3-pip
  - git
  - ansible

runcmd:
  - mkdir -p /app/python && cd /app/python && git clone ${app_repo}
  - chown -R cbeamer /app/python/hello-world
  #- cd /app/python/hello-world/infrastructure/ansible/ && ansible-playbook self-config.yml