#cloud-config
users:
  - name: cbeamer
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3GG+lA6Wm7XOk0hEgsip7qyNii/FWNO1YIlutbo4nA
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

packages:
  - python3

runcmd:
  - mkdir -p /app/python