---
- hosts: web
  become: yes
  gather_facts: no
  serial: 1
  vars:
    app_port: 8080
    app_host: '0.0.0.0'
    app_directory: '/app/python/'
  tasks:
    - name: Wait for hosts to become available
      wait_for_connection:
        delay: 30
        timeout: 900
        sleep: 5
        connect_timeout: 5
    - name: Sync application
      copy:
        src: /app/python/hello-world/helloworld.py
        dest: /app/python/
        mode: 0755
    ### Install requisite Python packages
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
    - name: Install FastAPI
      pip:
        name: fastapi
        state: present
    - name: Install Uvicorn
      pip:
        name: uvicorn
        state: present
    ## Create our Uvicorn service
    - name: Deploy Uvicorn systemd unit
      template:
        src: uvicorn.j2
        dest: /usr/lib/systemd/system/uvicorn.service
      notify:
        - restart-uvicorn
    ## Start uvicorn service  
    - name: Start Uvicorn
      systemd:
        name: uvicorn
        state: started
        enabled: True
        daemon-reload: True
  handlers:
    - name: restart-uvicorn
      systemd:
        name: uvicorn
        state: restarted
        enabled: True
        daemon-reload: True
      listen:
        - restart-uvicorn
